# runtime: python27
# api_version: 1
# threadsafe: yes

# handlers:
#   - url: /
#     static_files: dist/portfolio/index.html
#     upload: dist/portfolio/index.html
#   - url: /
#     static_dir: dist/portfolio

# skip_files:
#   - e2e/
#   - node_modules/
#   - src/
#   - ^(.*/)?\..*$
#   - ^(.*/)?.*\.json$
#   - ^(.*/)?.*\.md$
#   - ^(.*/)?.*\.yaml$
#   - ^LICENSE

runtime: python27
api_version: 1
threadsafe: yes

handlers:

  - url: /
    secure: always
    static_files: dist/portfolio/index.html
    upload: dist/portfolio/.*
  - url: /(.*\.js)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/portfolio/\1
    upload: dist/.*\.js
  - url: /(.*\.css)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/portfolio/\1
    mime_type: text/css
    upload: dist/.*\.css
  - url: /.*
    secure: always
    static_files: dist/portfolio/index.html
    upload: dist/.*
    
skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
